// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3FR1Q5o2shgpP5nyOrtVc9Q101OTVz18',
    appId: '1:584232749575:web:c3c44802104efbf38db8a2',
    messagingSenderId: '584232749575',
    projectId: 'fforward-704a0',
    authDomain: 'fforward-704a0.firebaseapp.com',
    databaseURL: 'https://fforward-704a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fforward-704a0.appspot.com',
    measurementId: 'G-JFNT5NHENL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpDIEfbe350dZHIyL3OGaYoYHyn5-j5uA',
    appId: '1:584232749575:android:97da20b182f3a7f68db8a2',
    messagingSenderId: '584232749575',
    projectId: 'fforward-704a0',
    databaseURL: 'https://fforward-704a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fforward-704a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMObKGxxN-ubWgRHwYSAmLuACsJ9ySQMU',
    appId: '1:584232749575:ios:f93449d36cc3a3fe8db8a2',
    messagingSenderId: '584232749575',
    projectId: 'fforward-704a0',
    databaseURL: 'https://fforward-704a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fforward-704a0.appspot.com',
    iosClientId: '584232749575-rmkgr6cg2jvi8bn9nkjt65695vmdn6ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.fforwardAdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMObKGxxN-ubWgRHwYSAmLuACsJ9ySQMU',
    appId: '1:584232749575:ios:f93449d36cc3a3fe8db8a2',
    messagingSenderId: '584232749575',
    projectId: 'fforward-704a0',
    databaseURL: 'https://fforward-704a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fforward-704a0.appspot.com',
    iosClientId: '584232749575-rmkgr6cg2jvi8bn9nkjt65695vmdn6ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.fforwardAdm',
  );
}
